POST http://aplikasi-auth-develop.up.railway.app/auth/register
Content-Type: application/json

{
    "name":"ferdie",
    "email":"ferdie@mail.com",
    "password":"password123"
}

### 
POST http://aplikasi-auth-develop.up.railway.app/auth/login
Content-Type: application/json

{
    "email":"ferdie@mail.com",
    "password":"password123"
}

###
GET http://localhost:3000/whoami
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InNhYnJpbmEiLCJlbWFpbCI6InNhYnJpbmFAbWFpbC5jb20iLCJpYXQiOjE2ODI2OTI2MDh9.VneW1WUp6Cupqe2H4zdYwwc18Ows-8OXnjd1nd1vTCY