POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"ferdie",
    "email":"ferdie@mail.com",
    "password":"password123"
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"ferdie@mail.com",
    "password":"password123"
}

###
GET http://localhost:3000/auth/whoami
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImZlcmRpZSIsImVtYWlsIjoiZmVyZGllQG1haWwuY29tIiwiaWF0IjoxNjg1ODcyNDIyfQ.CPVHhLpjS3FFlhpsqvP9e13_dFnza43L7MDdwvcGkx0